displayName: Traefik OIDC
type: middleware

import: github.com/lukaszraczylo/traefikoidc

summary: |
  Middleware adding OIDC authentication to traefik routes. Does what it says on the tin.
  Middleware has been tested with Auth0 and Logto. It should work with any OIDC provider.

testData:
  providerURL: https://accounts.google.com
  clientID: 1234567890.apps.googleusercontent.com
  clientSecret: secret
  callbackURL: /oauth2/callback
  logoutURL: /oauth2/logout
  scopes: # If not provided, default scopes will be used (openid, email, profile)
    - openid
    - email
    - profile
  allowedUserDomains: # If not provided - will rely entirely on the OIDC yes/no
    - raczylo.com
  allowedRolesAndGroups:
    - guest-endpoints
  sessionEncryptionKey: potato-secret
  forceHTTPS: false
  logLevel: debug # debug, info, warn, error
  rateLimit: 100 # Simple rate limiter to prevent brute force attacks
  excludedURLs: # Determines the list of URLs which are NOT a subject to authentication
    - /login # covers /login, /login/me, /login/reminder etc.
    - /my-public-data
